apiVersion: v2
name: mon-app
description: A simple Helm chart for deploying MyApp
version: 0.1.0
appVersion: "1.0"
keywords:
  - app
  - myapp
  - helm
maintainers:
  - name: jihed
    email: jihedbenamara02@gmail.com